services:
  store-app:
    build: .
    container_name: store-app
    ports:
      - "8888:8888"
 # Esta es el servicio de SonarQube para el análisis estático de Código
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
# Este servicio no tiene los plugins y hay que instalarlos manualmente, por eso se ha cambiado la imagen a una que ya los tiene instalados
# pero lo tienes aquí por si quieres probarlo con la imagen oficial de Nessus y luego instalar los plugins manualmente
# en vez de usar la imagen personalizada de abajo.
#  nessus:
#    image: nessus/nessus
#    container_name: nessus
#    ports:
#      - "8834:8834"
  nessus:  
     # Nessus Vulnerability Scanner  
    image: jmmedinac03/nessus_plugins  
        #    image: tenable/nessus:latest-ubuntu  
        #    restart: always  
        #    código de activacion nessus A2AA-KWWR-ZRSM-RW79-LBPH  
        #    acceso a la máquina por https://localhost:8834   
        #    creado usuario:usuario passwd:usuario  
    ports:  
      - 8834:8834  

